<?php
$headTitle = 'Edit user';
$this->headTitle($headTitle);

$form = $this->form;
$form->setAttribute('action', $this->url('admin/users', ['action' => 'edit', 'id' => $this->id]));
$form->prepare();
?>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h5 class="modal-title" id="myModalLabel">Are You sure?</h5>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">No</button>
                <button type="button" class="btn btn-danger" id="delete-user">Yes</button>
            </div>
        </div>
    </div>
</div>
<!-- Hidden form for delete user -->
<form action="<?= $this->url('admin/users', ['action' => 'delete', 'id' => $this->id]) ?>"
      method="post"
      class="delete-user-form"
>
    <button type="button">Yes</button>
</form>
<br>
<?= $this->partial('partial/breadcrumbTemplate', ['headTitle' => $headTitle]) ?>
<?= $this->flashMessenger()->render('success', ['success-message']) ?>
<br>
<div class="row">
    <div class="col-lg-5 col-md-6 col-sm-8">
        <?= $this->form()->openTag($form) ?>
        <div class="form-group">
            <div class="col-sm-2 text-left">
                <label>User:</label>
            </div>
            <div class="col-sm-10">
                <?= $this->getNameOrUsername($this, $this->user) ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-2 text-left">
                <label>Created:</label>
            </div>
            <div class="col-sm-10">
                <?= $this->user->getCreatedAt()->format('d F Y') ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-2 text-left">
                <?= $this->formLabel($form->get('role')) ?>
            </div>
            <div class="col-sm-10">
                <?= $this->formSelect($form->get('role')) ?>
                <?= $this->formElementErrors($form->get('role')) ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-2 text-left">
                <?= $this->formLabel($form->get('active')) ?>
            </div>
            <div class="col-sm-10">
                <?= $this->formRadio($form->get('active')) ?>
                <?= $this->formElementErrors($form->get('active')) ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-12">
                <?= $this->formSubmit($form->get('submit')) ?>
            </div>
        </div>
        <?= $this->form()->closeTag() ?>
    </div>
</div>
<hr>
<div class="row">
    <div class="col-sm-12">
        <button type="button" class="btn btn-danger pull-right" data-toggle="modal" data-target="#myModal">
            Delete <?= $this->user->getRole() ?>
        </button>
    </div>
</div>
