<?php
$headTitle = 'Manage users';
$this->headTitle($headTitle);
?>
<br>
<?= $this->partial('partial/breadcrumbTemplate', ['headTitle' => $headTitle]) ?>
<?= $this->flashMessenger()->render('success', ['success-message']) ?>
<br>
<div class="row">
    <div class="col-sm-3">
        <a class="btn btn-info btn-sm"
           role="button" data-toggle="collapse"
           href="#collapseExample"
           aria-expanded="false"
           aria-controls="collapseExample"
        >
            Admins list
        </a>
        <br>
        <div class="collapse" id="collapseExample">
            <div class="">
                <?php if (! $this->admins) : ?>
                    <br>
                    <div>List is empty</div>
                <?php else : ?>
                    <br>
                    <ol class="admins-list-ol">
                        <?php foreach ($this->admins as $admin) : ?>
                            <li>
                                <a href="<?= $this->url('admin/users', ['action' => 'edit', 'id' => (int)$admin->getId()]) ?>">
                                    <?= $this->escapeHtml($this->getNameOrUsername($this, $admin)) ?>
                                </a>
                            </li>
                        <?php endforeach; ?>
                    </ol>
                    <hr>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<br>
<div class="row">
    <div id="admin-search-user-form-box">
        <form action="/admin/users/search"
              class="navbar-form"
              role="search"
              method="post"
              id="admin-search-user-form"
        >
            <div class="input-group add-on">
                <input class="form-control" placeholder="Search user" name="admin-search-user" type="text" size="30">
                <div class="input-group-btn">
                    <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                </div>
            </div>
        </form>
        <ul id="admin-search-user-form-result" class="list-unstyled"></ul>
    </div>
</div>
