<?php
    echo $this->headStyle()->appendStyle('
        .portfolio { border: 1px solid #ddd; padding: 10px; border-radius: 3px; margin-bottom: 10px;}
        .portfolio:hover { border: 1px solid #999; }
    ');
?>
<?php
$headTitle = 'Portfolio';
$this->headTitle($headTitle);
?>
<br>
<h4><?= $headTitle ?></h4>
<br>
<div class="row">
    <div class="col-sm-4">
        <div class="portfolio">
            <a href="http://simplesite.96.lt" target="_blank">
                <img src="/img/portfolio/simplesite.png"
                     alt="site-image"
                     width="100%"
                     height="100%"
                     class="img-responsive"
                >
            </a>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="portfolio">
            <a href="http://jokeshop.96.lt" target="_blank">
                <img src="/img/portfolio/jokeshop.png"
                     alt="site-image"
                     width="100%"
                     height="100%"
                     class="img-responsive"
                >
            </a>
        </div>
    </div>
</div>
