<?php
$headTitle = 'Manage statuses';
$this->headTitle($headTitle);
?>
<br>
<?= $this->partial('partial/breadcrumbTemplate', ['headTitle' => $headTitle]) ?>
<?= $this->flashMessenger()->render('success', ['success-message']) ?>
<br>
<div class="row">
    <div id="admin-search-status-form-box">
        <form action="/admin/statuses"
              class="navbar-form"
              role="search"
              method="post"
              id="admin-search-status-form"
        >
            <div class="input-group add-on">
                <input class="form-control" placeholder="Search status" name="search" type="text" size="30">
                <div class="input-group-btn">
                    <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                </div>
            </div>
        </form>
        <ul id="admin-search-status-form-result" class="list-unstyled"></ul>
    </div>
</div>
<?php if (! $this->searchResult) : ?>
<p><?= $this->escapeHtml($this->message) ?></p>
<?php else : ?>
<p>Your search for "<?= $this->escapeHtml($this->search) ?>"</p>
<br>
<div class="table-responsive">
    <table class="table table-striped table-hover">
        <tr>
            <th>User</th>
            <th>Created at</th>
            <th>Content</th>
            <th>Action</th>
        </tr>
        <?php foreach ($this->searchResult as $value) : ?>
        <tr>
            <td><?= $this->escapeHtml($this->getNameOrUsername($this, $value->getUser())) ?></td>
            <td><?= $this->escapeHtml($value->getCreatedAt()->format('d F Y')) ?></td>
            <td><?= nl2br($this->escapeHtml($value->getContent())) ?></td>
            <td>
                <form action="<?= $this->url('admin/statuses', ['action' => 'delete', 'id' => (int)$value->getId()]) ?>"
                      method="post"
                      class="delete-form admin-delete-status"
                >
                    <button>Delete</button>
                </form>
            </td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>
<?php endif; ?>

