<?php if ($this->pageCount): ?>
    <div class="text-center">
        <ul class="pagination pagination-sm">
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li>
                    <a href="<?= $this->url($this->route, ['page' => $this->previous]) ?>">&laquo;</a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#" onclick="return false">&laquo;</a>
                </li>
            <?php endif ?>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page !== $this->current): ?>
                    <li>
                        <a href="<?= $this->url($this->route, ['page' => $page]) ?>">
                            <?= $page ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="active">
                        <a href="#" onclick="return false"><?= $page ?></a>
                    </li>
                <?php endif ?>
            <?php endforeach ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li>
                    <a href="<?= $this->url($this->route, ['page' => $this->next]) ?>">&raquo;</a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#" onclick="return false">&raquo;</a>
                </li>
            <?php endif ?>
        </ul>
    </div>
<?php endif ?>
