<div class="media">
    <a href="<?= $this->url('profile', ['username' => $this->user->getUsername()]) ?>" class="pull-left">
        <img class="media-object",
             alt="<?= $this->getNameOrUsername($this, $this->user) ?>"
             src="<?= $this->user->getImage() ?>"
             width="40"
             height="40"
        >
    </a>
    <div class="media-body">
        <h5 class="media-heading">
            <a href="<?= $this->url('profile', ['username' => $this->user->getUsername()]) ?>">
                <?= $this->getNameOrUsername($this, $this->user) ?>
            </a>
        </h5>
        <div>
            <?= $this->user->getLocation() ? $this->escapeHtml($this->user->getLocation()) : false; ?>
        </div>
    </div>
</div>
