<div class="media">
    <a href="<?= $this->url('profile', ['username' => $this->user->getUsername()]) ?>"
       class="pull-left user-profile-img"
       data-active="<?= (int)$this->user->getActive() ?>"
    >
        <img class="media-object",
             src="<?= $this->getImage($this, $this->user->getImage()) ?>"
             alt="profile-image"
             width="40"
             height="40"
        >
    </a>
    <div class="media-body">
        <h5 class="media-heading">
            <a href="<?= $this->url('profile', ['username' => $this->user->getUsername()]) ?>"
               class="user-profile-name"
               data-active="<?= (int)$this->user->getActive() ?>"
            >
                <?= $this->getNameOrUsername($this, $this->user) ?>
            </a>
            <div class="not-active"></div>
        </h5>
        <div>
            <?= $this->user->getLocation() ? $this->escapeHtml($this->user->getLocation()) : false; ?>
        </div>
    </div>
</div>
